/*
 * NO INCLUDE GUARD AS THE FILE IS ONLY INCLUDED IN DIAGNOSIS.H
 * */

/* CONFIGURATION PARAMTERS */
#define DGN_CONF_OPEN_SPEED				1
#define DGN_CONF_CLOSE_SPEED			2
#define DGN_CONF_OPEN_TIME				3
#define DGN_CONF_MAX_CURRENT			4
#define DGN_CONF_OBSTR_CURRENT_O		5
#define DGN_CONF_OBSTR_CURRENT_C		6
#define DGN_CONF_CLOSE_TIMEOUT			7
#define DGN_CONF_MAX_DOOR_POS			8
#define DGN_CONF_EDGE_SENS_ACTIVE		9
#define DGN_CONF_EDGE_SENS_VOLTAGE		10
#define DGN_CONF_CALIB_FREQ				11
#define DGN_CONF_CLOSE_ATTEMPTS			12
#define DGN_CONF_OPEN_ATTEMPTS			13
#define DGN_CONF_MAX_SPEED				14
#define DGN_MIN_DEPLOYMENT_POS			15
#define DGN_MIN_DEPLOYMENT_POS			16
#define DGN_MIN_DEPLOYMENT_POS			17
#define DGN_MIN_DEPLOYMENT_POS			18
#define DGN_MIN_DEPLOYMENT_POS			19
#define DGN_SPARE_0						20

/* ON/OFF CONFIGURATION */
#define DGN_MIN_DEPLOYMENT_POS			21
#define DGN_MIN_DEPLOYMENT_POS			22
#define DGN_MIN_DEPLOYMENT_POS			23
#define DGN_MIN_DEPLOYMENT_POS			24
#define DGN_MIN_DEPLOYMENT_POS			25
#define DGN_MIN_DEPLOYMENT_POS			26
#define DGN_MIN_DEPLOYMENT_POS			27
#define DGN_MIN_DEPLOYMENT_POS			28
#define DGN_MIN_DEPLOYMENT_POS			29

/* ADVANCED PARAMETERS */
#define DGN_MIN_DEPLOYMENT_POS			30
#define DGN_MIN_DEPLOYMENT_POS			31
#define DGN_MIN_DEPLOYMENT_POS			32
#define DGN_MIN_DEPLOYMENT_POS			33
#define DGN_MIN_DEPLOYMENT_POS			34
#define DGN_MIN_DEPLOYMENT_POS			35
#define DGN_MIN_DEPLOYMENT_POS			36
#define DGN_MIN_DEPLOYMENT_POS			37
#define DGN_MIN_DEPLOYMENT_POS			38
#define DGN_ADV_SPARE_1					39

/* ADVANCED PARAMETERS */
#define DGN_MIN_DEPLOYMENT_POS			40
#define DGN_MIN_DEPLOYMENT_POS			41
#define DGN_MIN_DEPLOYMENT_POS			42
#define DGN_MIN_DEPLOYMENT_POS			43
#define DGN_MIN_DEPLOYMENT_POS			44
#define DGN_MIN_DEPLOYMENT_POS			45
#define DGN_MIN_DEPLOYMENT_POS			46
#define DGN_MIN_DEPLOYMENT_POS			47
#define DGN_ADV_SPARE_2					48
#define DGN_ADV_SPARE_3					49
#define DGN_ADV_SPARE_4					50
#define DGN_ADV_SPARE_5					51
#define DGN_ADV_SPARE_6					52
#define DGN_ADV_SPARE_7					53
#define DGN_ADV_SPARE_8					54

/* CALIBRATION PARAMETERS */
#define DGN_MIN_DEPLOYMENT_POS			55
#define DGN_MIN_DEPLOYMENT_POS			56
#define DGN_CAL_SPARE1					57
#define DGN_CAL_SPARE2					58

/* CALIBRATION PARAMETERS */
#define DGN_MIN_DEPLOYMENT_POS			59
#define DGN_MIN_DEPLOYMENT_POS			60
#define DGN_MIN_DEPLOYMENT_POS			61
#define DGN_MIN_DEPLOYMENT_POS			62
#define DGN_MIN_DEPLOYMENT_POS			63
#define DGN_CAL_SPARE0					64

/* INPUT SELECTION */
#define DGN_MIN_DEPLOYMENT_POS			65
#define DGN_MIN_DEPLOYMENT_POS			66
#define DGN_MIN_DEPLOYMENT_POS			67
#define DGN_MIN_DEPLOYMENT_POS			68
#define DGN_MIN_DEPLOYMENT_POS			69
#define DGN_MIN_DEPLOYMENT_POS			70
#define DGN_MIN_DEPLOYMENT_POS			71
#define DGN_MIN_DEPLOYMENT_POS			72
#define DGN_MIN_DEPLOYMENT_POS			73
#define DGN_MIN_DEPLOYMENT_POS			74
#define DGN_MIN_DEPLOYMENT_POS			75
#define DGN_MIN_DEPLOYMENT_POS			76

/* OUTPUT SELECTION */
#define DGN_MIN_DEPLOYMENT_POS			77
#define DGN_MIN_DEPLOYMENT_POS			78
#define DGN_MIN_DEPLOYMENT_POS			79
#define DGN_MIN_DEPLOYMENT_POS			80
#define DGN_SPARE_1						81
#define DGN_SPARE_2						82
#define DGN_SPARE_3						83
#define DGN_SPARE_4						84
#define DGN_SPARE_5						85
#define DGN_SPARE_6						86
#define DGN_SPARE_7						87
#define DGN_SPARE_8						88

/* OUTPUT SELECTION */
#define DGN_MIN_DEPLOYMENT_POS			89
#define DGN_MIN_DEPLOYMENT_POS			90
#define DGN_MIN_DEPLOYMENT_POS			91
#define DGN_MIN_DEPLOYMENT_POS			92

/* MANUFACTURE DATA */
#define DGN_MIN_DEPLOYMENT_POS			93
#define DGN_MIN_DEPLOYMENT_POS			94

/* ERRORS */
#define DGN_FEATURE_ERRORS				95

/* FEATURE */
#define DGN_FEATURE_COMMAND				96
#define DGN_FEATURE_WAVEFORM			97
#define DGN_FEATURE_SPARE0				98
#define DGN_FEATURE_SPARE1				99

/* STATISTICS */
#define DGN_MIN_DEPLOYMENT_POS			100
#define DGN_MIN_DEPLOYMENT_POS			101
#define DGN_MIN_DEPLOYMENT_POS			102
#define DGN_MIN_DEPLOYMENT_POS			103
#define DGN_MIN_DEPLOYMENT_POS			104
#define DGN_MIN_DEPLOYMENT_POS			105
#define DGN_MIN_DEPLOYMENT_POS			119

/* ACTUAL CONTROLLER STATUS */
#define DGN_MIN_DEPLOYMENT_POS			106
#define DGN_MIN_DEPLOYMENT_POS			107
#define DGN_MIN_DEPLOYMENT_POS			108
#define DGN_MIN_DEPLOYMENT_POS			109
#define DGN_MIN_DEPLOYMENT_POS			110
#define DGN_MIN_DEPLOYMENT_POS			111
#define DGN_MIN_DEPLOYMENT_POS			112
#define DGN_MIN_DEPLOYMENT_POS			113
#define DGN_MIN_DEPLOYMENT_POS			114
#define DGN_MIN_DEPLOYMENT_POS			115
#define DGN_MIN_DEPLOYMENT_POS			116
#define DGN_MIN_DEPLOYMENT_POS			117
#define DGN_MIN_DEPLOYMENT_POS			118
#define DGN_MIN_DEPLOYMENT_POS			120
#define DGN_MIN_DEPLOYMENT_POS			121
#define DGN_MIN_DEPLOYMENT_POS			122

/* CTRL */
#define DGN_MIN_DEPLOYMENT_POS			123
#define DGN_MIN_DEPLOYMENT_POS			124
#define DGN_MIN_DEPLOYMENT_POS			125
